services:

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - ${DOCKER_MYSQL_PORT:-3306}:3306
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 3
    restart: always
    networks:
      - estudo

  app:
    build:
      context: .
    entrypoint: ["laravel-entrypoint.sh"]
    command: ["php-fpm"]
    ports:
      - ${DOCKER_FPM_PORT:-9000}:9000
    environment:
      USER_ID: ${DOCKER_USER_ID}
      GROUP_ID: ${DOCKER_GROUP_ID}
    volumes:
      - .:/var/www/html
      - ./tools/php-fpm/laravel.conf:/usr/local/etc/php-fpm.d/laravel.conf
      - ./tools/scripts/laravel-entrypoint.sh:/usr/local/bin/laravel-entrypoint.sh
    healthcheck:
      test: ["CMD-SHELL", "netstat -an | grep 9000"]
      interval: 5s
      timeout: 5s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - estudo

  http:
    image: nginx:alpine
    ports:
      - ${DOCKER_HTTP_PORT:-80}:80
      - ${DOCKER_HTTPS_PORT:-443}:443
    volumes:
      - .:/var/www/html
      - ./tools/nginx/conf.d:/etc/nginx/conf.d
      - ./tools/nginx/default.d:/etc/nginx/default.d
      - ./tools/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      app:
        condition: service_healthy
    restart: always
    networks:
        - estudo

networks:
  estudo:
    driver: bridge
volumes:
  db:
